"""created comments table

Revision ID: c1c10ead0b4c
Revises: 5f5312a4c23e
Create Date: 2020-09-27 19:41:51.660177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c10ead0b4c'
down_revision = '5f5312a4c23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_username'), 'comments', ['username'], unique=False)
    op.drop_table('post_delete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_delete',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_delete_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='post_delete_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_delete_pkey')
    )
    op.drop_index(op.f('ix_comments_username'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
