"""created comments table

Revision ID: edf152746247
Revises: c1c10ead0b4c
Create Date: 2020-09-27 19:50:25.309648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf152746247'
down_revision = 'c1c10ead0b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_comments_name'), 'comments', ['name'], unique=False)
    op.drop_index('ix_comments_username', table_name='comments')
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_comments_username', 'comments', ['username'], unique=False)
    op.drop_index(op.f('ix_comments_name'), table_name='comments')
    op.drop_column('comments', 'name')
    # ### end Alembic commands ###
